name: DevSecOps Security Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan dependencies
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "DevSecOps Demo"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Scan filesystem with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          severity: "HIGH,CRITICAL"
          exit-code: "1"
